# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3efb5974f489f838b7e440a6a7f3a2a8613474a502bcc0cbedd3525bd6a515c57e4d31ef5e59b1c9f85acbfca5c103125f51c93031eaae7b9fe751514bd6a712

test:
  secret_key_base: b62df5c0c486b501daa64cb36c82699b88bc41005709aafec910577bb1be8a173acf493ec710870cdbe4996758790132b1bcc8efabfb5480a71c615d01a3d0b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
